org.gradle.jvmargs=-Xmx4g -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.java.home=/Users/ctme/Library/Java/JavaVirtualMachines/corretto-17.0.12/Contents/Home

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
